"""file_detail_model

Revision ID: 2be8e017b4a8
Revises: f1c24864ca94
Create Date: 2021-03-06 13:51:55.863834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be8e017b4a8'
down_revision = 'f1c24864ca94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_detail',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('owner', sa.Integer(), nullable=False),
        sa.Column('signed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['owner'], ['user.id'], name='user_id_fk'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('filename', 'owner', name='filename_owner_uc'),
        mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_detail')
    # ### end Alembic commands ###
